In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
x =  np.random.uniform(-3,3,size=100)
X = x.reshape(-1,1)
y = 0.5 * x**2 + x + 2 + np.random.normal(0,1,100)

In [3]:
# PolynomialFeatures是sklearn中用于生成多项式的类
from sklearn.preprocessing import PolynomialFeatures

In [4]:
poly =  PolynomialFeatures(degree=2)

In [24]:
poly.fit(X)
# 将X转换成多项式的特征
out = poly.transform(X)

In [25]:
# 对于一维向量，deggre==2的时候结果是三列，第一列是x的零次方，第二列是x的1次方，第三列的x的2次方
out[:5,:]

array([[ 1.        ,  0.65736675,  0.43213105],
       [ 1.        ,  2.57552531,  6.63333063],
       [ 1.        , -2.35864178,  5.56319106],
       [ 1.        ,  0.27335202,  0.07472133],
       [ 1.        , -1.37257952,  1.88397454]])

In [26]:
# 对于一维向量，当degree==3的时候，计算结果是四列
poly3 = PolynomialFeatures(degree=3)
poly3.fit(X)
out3 = poly3.transform(X)

In [27]:
out3[:5,:]

array([[  1.        ,   0.65736675,   0.43213105,   0.28406858],
       [  1.        ,   2.57552531,   6.63333063,  17.08431093],
       [  1.        ,  -2.35864178,   5.56319106, -13.12157488],
       [  1.        ,   0.27335202,   0.07472133,   0.02042523],
       [  1.        ,  -1.37257952,   1.88397454,  -2.58590486]])

In [28]:
X2 = x.reshape(-1,2)

In [30]:
poly_v2_d2 =  PolynomialFeatures(degree=2)

In [37]:
poly_v2_d2.fit(X2)
out_v2_d2 = poly_v2_d2.transform(X2)

In [38]:
# 对于2个特征的数据，degree==2的时候生成的多项式矩阵为六列，
# 分别表示0， X1， X2， X1**2， X1*X2， X2**2
# 即，输入的矩阵的每一个纬度X1, X2，转化为各个次幂的多项式。指数级增长
out_v2_d2[:2,:]

array([[ 1.        ,  0.65736675,  2.57552531,  0.43213105,  1.69306471,
         6.63333063],
       [ 1.        , -2.35864178,  0.27335202,  5.56319106, -0.6447395 ,
         0.07472133]])